import { IProject, ProjectStatus } from "./project.interface";

const PROJECT_ITEMS: IProject[] = [
  {
    name: "what-time",
    title: "What Time",
    type: "Web Tool",
    description: "Web tool for showing time.",
    imagePreview: "",
    image: "",
    link: "/tools/what-time",
    year: 2025,
    status: ProjectStatus.Active,
  },
  {
    name: "entity-driven-architecture",
    title: "Entity Driven Architecture",
    type: "Style Guide",
    description: "Entity Driven Architecture.",
    imagePreview: "",
    image: "",
    link: "https://github.com/Tertiumnon/entity-driven-architecture",
    year: 2023,
    status: ProjectStatus.Inactive,
  },
  {
    name: "git-style-guide",
    title: "Git Style Guide",
    type: "Style Guide",
    description: "Git Style Guide.",
    imagePreview: "",
    image: "",
    link: "https://github.com/Tertiumnon/git-style-guide",
    year: 2022,
    status: ProjectStatus.Inactive,
  },
  {
    name: "rest-api-style-guide",
    title: "REST API Style Guide",
    type: "Style Guide",
    description: "REST API Style Guide.",
    imagePreview: "",
    image: "",
    link: "https://github.com/Tertiumnon/rest-api-style-guide",
    year: 2022,
    status: ProjectStatus.Inactive,
  },
  {
    name: "frontend-style-guide",
    title: "Frontend Style Guide",
    type: "Style Guide",
    description: "Frontend Style Guide.",
    imagePreview: "",
    image: "",
    link: "https://github.com/Tertiumnon/frontend-style-guide",
    year: 2016,
    status: ProjectStatus.Inactive,
  },
  {
    name: "cheatsheets",
    title: "Cheatsheets",
    type: "Knowledge Base",
    description: "Cheatsheets for programmers.",
    imagePreview: "",
    image: "",
    link: "https://github.com/Tertiumnon/cheatsheets",
    year: 2017,
    status: ProjectStatus.Active,
  },
  {
    name: "send-text-to-form",
    title: "Send Text To Form",
    type: "Chrome Extension",
    description: "Chrome extension for sending text to form on any page.",
    imagePreview: "",
    image: "/assets/images/projects/send-text-to-form-web-ext/2017-send-text-to-form-web-ext.png",
    link: "https://chrome.google.com/webstore/detail/send-text-to-form/oapmpchdbmlmblgeambfmcmmoalbgooi",
    year: 2017,
    status: ProjectStatus.Inactive,
  },
  {
    name: "mw-deploy",
    title: "MediaWiki Deploy",
    type: "NodeJS Application",
    description: "NodeJS application for deploying MediaWiki pages.",
    imagePreview: "",
    image: "",
    link: "https://github.com/Tertiumnon/mw-deploy",
    year: 2017,
    status: ProjectStatus.Inactive,
  },
  {
    name: "bookmarks-manager",
    title: "Bookmarks Manager",
    type: "Firefox Extension",
    description: "Firefox extension for bookmarks organizing.",
    imagePreview: "",
    image: "",
    link: "https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager/",
    year: 2017,
    status: ProjectStatus.Active,
  },
  {
    name: "tertium-js-snippets",
    title: "Tertium JS Snippets",
    type: "VSCode Extension",
    description: "Visual Studio Code extension for JavaScript autocompletion.",
    imagePreview: "",
    image: "",
    link: "https://marketplace.visualstudio.com/items?itemName=tertiumnon.tertium-js-snippets",
    year: 2019,
    status: ProjectStatus.Active,
  },
  {
    name: "json-all-to-one",
    title: "JSON All to One",
    type: "NodeJS Package",
    description: "NodeJS script for JSON files concatenation.",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/json-all-to-one",
    year: 2019,
    status: ProjectStatus.Inactive,
  },
  {
    name: "json-to-sql",
    title: "JSON to SQL",
    type: "NodeJS Package",
    description: "NodeJS script that creates SQL script from JSON file.",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/json-to-sql-script",
    year: 2019,
    status: ProjectStatus.Inactive,
  },
  {
    name: "tertium-countries",
    title: "@tertium/countries",
    type: "NodeJS Package",
    description: "NodeJS module for country codes.",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/@tertium/countries",
    year: 2021,
    status: ProjectStatus.Inactive,
  },
  {
    name: "tertium-icons",
    title: "Tertium Icons",
    type: "NodeJS Package",
    description: "SVG and font icons.",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/tertium.icons",
    year: 2017,
    status: ProjectStatus.Inactive,
  },
  {
    name: "senior-pomodoro",
    title: "Senior Pomodoro",
    type: "Desktop Application",
    description: "Pomodoro timer for coders.",
    imagePreview: "",
    image: "",
    link: "",
    year: 2020,
    status: ProjectStatus.Inactive,
  },
];

export default PROJECT_ITEMS;
