import { IProject, ProjectStatus } from './project.interface';

const PROJECT_ITEMS: IProject[] = [
  {
    name: 'cheatsheets',
    title: 'Cheatsheets',
    type: 'Knowledge base',
    description: 'Cheatsheets for programmers',
    imagePreview: '',
    image: '',
    link: 'https://github.com/Tertiumnon/cheatsheets',
    year: 2017,
    status: ProjectStatus.Active,
  },
  {
    name: 'send-text-to-form',
    title: 'Send Text To Form',
    type: 'Web extension',
    description: 'Chrome extension for sending text to form on any page',
    imagePreview: '',
    image:
      '/assets/images/projects/send-text-to-form-web-ext/2017-send-text-to-form-web-ext.png',
    link: 'https://chrome.google.com/webstore/detail/send-text-to-form/oapmpchdbmlmblgeambfmcmmoalbgooi',
    year: 2017,
    status: ProjectStatus.Inactive,
  },
  {
    name: 'mw-deploy',
    title: 'MediaWiki Deploy',
    type: 'NodeJS application',
    description: 'NodeJS application for deploying MediaWiki pages',
    imagePreview: '',
    image: '',
    link: 'https://github.com/Tertiumnon/mw-deploy',
    year: 2017,
    status: ProjectStatus.Inactive,
  },
  {
    name: 'bookmarks-manager',
    title: 'Bookmarks Manager',
    type: 'Web extension',
    description: 'Firefox extension for bookmarks organizing',
    imagePreview: '',
    image: '',
    link: 'https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager/',
    year: 2017,
    status: ProjectStatus.Active,
  },
  {
    name: 'tertium-js-snippets',
    title: 'Tertium JS Snippets',
    type: 'App extension',
    description: 'Visual Studio Code extension for JavaScript autocompletion',
    imagePreview: '',
    image: '',
    link: 'https://marketplace.visualstudio.com/items?itemName=tertiumnon.tertium-js-snippets',
    year: 2019,
    status: ProjectStatus.Active,
  },
  {
    name: 'json-all-to-one',
    title: 'JSON All to One',
    type: 'NodeJS package',
    description: 'NodeJS script for JSON files concatenation',
    imagePreview: '',
    image: '',
    link: 'https://www.npmjs.com/package/json-all-to-one',
    year: 2019,
    status: ProjectStatus.Inactive,
  },
  {
    name: 'json-to-sql',
    title: 'JSON to SQL',
    type: 'NodeJS package',
    description: 'NodeJS script that creates SQL script from JSON file',
    imagePreview: '',
    image: '',
    link: 'https://www.npmjs.com/package/json-to-sql-script',
    year: 2019,
    status: ProjectStatus.Inactive,
  },
  {
    name: 'tertium-countries',
    title: '@tertium/countries',
    type: 'NodeJS package',
    description: 'NodeJS module for country codes',
    imagePreview: '',
    image: '',
    link: 'https://www.npmjs.com/package/@tertium/countries',
    year: 2021,
    status: ProjectStatus.Active,
  },
  {
    name: 'tertium-icons',
    title: 'Tertium Icons',
    type: 'NodeJS package',
    description: 'SVG and font icons',
    imagePreview: '',
    image: '',
    link: 'https://www.npmjs.com/package/tertium.icons',
    year: 2017,
    status: ProjectStatus.Inactive,
  },
  {
    name: 'senior-pomodoro',
    title: 'Senior Pomodoro',
    type: 'Desktop application',
    description: 'Pomodoro timer for coders',
    imagePreview: '',
    image: '',
    link: '',
    year: 2020,
    status: ProjectStatus.Active,
  },
];

export default PROJECT_ITEMS;
