import { IProject, ProjectStatus } from "./shared/project/project";

const PROJECTS: IProject[] = [
  {
    title: "Cheatsheets",
    type: "Website",
    description: "Cheatsheets for programmers",
    imagePreview: "",
    image: "",
    link: "http://cheatsheets.origin-creative-studio.com",
    year: 2017,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Send Text To Form",
    type: "Web extension",
    description: "Chrome extension for sending text to form on any page",
    imagePreview: "",
    image: "/assets/images/projects/send-text-to-form-web-ext/2017-send-text-to-form-web-ext.png",
    link: "https://chrome.google.com/webstore/detail/send-text-to-form/oapmpchdbmlmblgeambfmcmmoalbgooi",
    year: 2017,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Bookmarks Manager",
    type: "Web extension",
    description: "Firefox extension for bookmarks organizing",
    imagePreview: "",
    image: "",
    link: "https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager/",
    year: 2017,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "Tertium JS Snippets",
    type: "App extension",
    description: "Visual Studio Code extension for JavaScript autocompletion",
    imagePreview: "",
    image: "",
    link: "https://marketplace.visualstudio.com/items?itemName=vittertiumnon.tertium-js-snippets",
    year: 2019,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "json-all-to-one",
    type: "NodeJS package",
    description: "NodeJS script for JSON files concatenation",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/json-all-to-one",
    year: 2019,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "json-to-sql",
    type: "NodeJS package",
    description: "NodeJS script that creates SQL script from JSON file",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/json-to-sql-script",
    year: 2019,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "@tertium/countries",
    type: "NodeJS package",
    description: "NodeJS module for country codes",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/@tertium/countries",
    year: 2021,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "Tertium Icons",
    type: "NodeJS package",
    description: "SVG and font icons",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/tertium.icons",
    year: 2017,
    workTypes: ["design", "coding"],
    status: ProjectStatus.Inactive,
  },
];

export default PROJECTS;
