import { IProject, ProjectStatus } from "./shared/project/project";

const PROJECTS: IProject[] = [
  {
    title: "Kvartal 2000",
    type: "Website",
    description: "Website for a real estate agency",
    imagePreview: "/assets/images/projects/kvartal2000-web/2008-kvartal2000-web-preview.png",
    image: "/assets/images/projects/kvartal2000-web/2008-kvartal2000-web.png",
    link: "",
    year: 2008,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Kvartal 2000",
    type: "Website",
    description: "Website for a real estate agency",
    imagePreview: "/assets/images/projects/kvartal2000-web/2009-kvartal2000-web-preview.png",
    image: "/assets/images/projects/kvartal2000-web/2009-kvartal2000-web.png",
    link: "",
    year: 2009,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Locman Kvartir",
    type: "Website",
    description: "Website for a real estate listing",
    imagePreview: "/assets/images/projects/locman-kvartir-web/2008-locman-kvartir-web-preview.png",
    image: "/assets/images/projects/locman-kvartir-web/2008-locman-kvartir-web.png",
    link: "",
    year: 2010,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Arsenal SB",
    type: "Website",
    description: "Website for CCTV sales company",
    imagePreview: "/assets/images/projects/arsenal-sb-web/2011-arsenal-sb-web-preview.png",
    image: "/assets/images/projects/arsenal-sb-web/2011-arsenal-sb-web.png",
    link: "",
    year: 2011,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "PROvision",
    type: "Website",
    description: "Website for CCTV manufacturing company",
    imagePreview: "/assets/images/projects/provision-web/2012-provision-web-preview.png",
    image: "/assets/images/projects/provision-web/2012-provision-web.png",
    link: "",
    year: 2012,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Alert CCTV",
    type: "Website",
    description: "Website for CCTV manufacturing company",
    imagePreview: "/assets/images/projects/alert-cctv-web/2012-alert-cctv-web-preview.png",
    image: "/assets/images/projects/alert-cctv-web/2012-alert-cctv-web.png",
    link: "",
    year: 2012,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Katerinafee Shop",
    type: "Website",
    description: "Online shop for a fashion designer",
    imagePreview: "",
    image: "",
    link: "",
    year: 2013,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Katerinafee",
    type: "Website",
    description: "Website for a fashion designer",
    imagePreview: "",
    image: "",
    link: "http://www.katerinafee.com",
    year: 2014,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Enso Photo",
    type: "Website",
    description: "Photographer portfolio website",
    imagePreview: "/assets/images/projects/enso-photo-web/2014-enso-photo-web-preview.png",
    image: "/assets/images/projects/enso-photo-web/2014-enso-photo-web.png",
    link: "",
    year: 2014,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "JKH Service",
    type: "Website",
    description: "Landing website for a building company",
    imagePreview: "",
    image: "",
    link: "",
    year: 2018,
    workTypes: ["design"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Cheatsheets",
    type: "Website",
    description: "Cheatsheets for programmers",
    imagePreview: "",
    image: "",
    link: "http://cheatsheets.origin-creative-studio.com",
    year: 2017,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Send Text To Form",
    type: "Web extension",
    description: "Chrome extension for sending text to form on any page",
    imagePreview: "",
    image: "/assets/images/projects/send-text-to-form-web-ext/2017-send-text-to-form-web-ext.png",
    link: "https://chrome.google.com/webstore/detail/send-text-to-form/oapmpchdbmlmblgeambfmcmmoalbgooi",
    year: 2017,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Bookmarks Manager",
    type: "Web extension",
    description: "Firefox extension for bookmarks organizing",
    imagePreview: "",
    image: "",
    link: "https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager/",
    year: 2017,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "Tertium JS Snippets",
    type: "App extension",
    description: "Visual Studio Code extension for JavaScript autocompletion",
    imagePreview: "",
    image: "",
    link: "https://marketplace.visualstudio.com/items?itemName=vittertiumnon.tertium-js-snippets",
    year: 2019,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "TASS Wiki",
    type: "Website",
    description: "Information agency wiki website",
    imagePreview: "",
    image: "",
    link: "",
    year: 2015,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "TASS HRStat",
    type: "Website",
    description: "Information agency productivity statistics website",
    imagePreview: "",
    image: "",
    link: "",
    year: 2016,
    workTypes: ["layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "json-all-to-one",
    type: "NodeJS package",
    description: "NodeJS script for JSON files concatenation",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/json-all-to-one",
    year: 2019,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "json-to-sql",
    type: "NodeJS package",
    description: "NodeJS script that creates SQL script from JSON file",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/json-to-sql-script",
    year: 2019,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "@tertium/countries",
    type: "NodeJS package",
    description: "NodeJS module for country codes",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/@tertium/countries",
    year: 2021,
    workTypes: ["coding"],
    status: ProjectStatus.Active,
  },
  {
    title: "Tertium Icons",
    type: "NodeJS package",
    description: "SVG and font icons",
    imagePreview: "",
    image: "",
    link: "https://www.npmjs.com/package/tertium.icons",
    year: 2017,
    workTypes: ["design", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Zip24 Service",
    type: "Website",
    description: "Brewery equipment",
    imagePreview: "",
    image: "",
    link: "https://zip24.ru",
    year: 2020,
    workTypes: ["coding"],
    status: ProjectStatus.Inactive,
  },
];

export default PROJECTS;
