import { IProject, ProjectStatus } from "./shared/project/project";

export const PORTFOLIO_PROJECTS: IProject[] = [
  {
    title: "Kvartal 2000",
    type: "Website",
    description: "Website for a real estate agency",
    imagePreview: "/assets/images/projects/kvartal2000-web/2008-kvartal2000-web-preview.png",
    image: "/assets/images/projects/kvartal2000-web/2008-kvartal2000-web.png",
    link: "",
    year: 2008,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Kvartal 2000",
    type: "Website",
    description: "Website for a real estate agency",
    imagePreview: "/assets/images/projects/kvartal2000-web/2009-kvartal2000-web-preview.png",
    image: "/assets/images/projects/kvartal2000-web/2009-kvartal2000-web.png",
    link: "",
    year: 2009,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Locman Kvartir",
    type: "Website",
    description: "Website for a real estate listing",
    imagePreview: "/assets/images/projects/locman-kvartir-web/2008-locman-kvartir-web-preview.png",
    image: "/assets/images/projects/locman-kvartir-web/2008-locman-kvartir-web.png",
    link: "",
    year: 2010,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Arsenal SB",
    type: "Website",
    description: "Website for CCTV sales company",
    imagePreview: "/assets/images/projects/arsenal-sb-web/2011-arsenal-sb-web-preview.png",
    image: "/assets/images/projects/arsenal-sb-web/2011-arsenal-sb-web.png",
    link: "",
    year: 2011,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "PROvision",
    type: "Website",
    description: "Website for CCTV manufacturing company",
    imagePreview: "/assets/images/projects/provision-web/2012-provision-web-preview.png",
    image: "/assets/images/projects/provision-web/2012-provision-web.png",
    link: "",
    year: 2012,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Alert CCTV",
    type: "Website",
    description: "Website for CCTV manufacturing company",
    imagePreview: "/assets/images/projects/alert-cctv-web/2012-alert-cctv-web-preview.png",
    image: "/assets/images/projects/alert-cctv-web/2012-alert-cctv-web.png",
    link: "",
    year: 2012,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Katerinafee Shop",
    type: "Website",
    description: "Online shop for a fashion designer",
    imagePreview: "",
    image: "",
    link: "",
    year: 2013,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Katerinafee",
    type: "Website",
    description: "Website for a fashion designer",
    imagePreview: "",
    image: "",
    link: "http://www.katerinafee.com",
    year: 2014,
    workTypes: ["design", "layout"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Enso Photo",
    type: "Website",
    description: "Photographer portfolio website",
    imagePreview: "/assets/images/projects/enso-photo-web/2014-enso-photo-web-preview.png",
    image: "/assets/images/projects/enso-photo-web/2014-enso-photo-web.png",
    link: "",
    year: 2014,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "JKH Service",
    type: "Website",
    description: "Landing website for a building company",
    imagePreview: "",
    image: "",
    link: "",
    year: 2018,
    workTypes: ["design"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "TASS Wiki",
    type: "Website",
    description: "Information agency wiki website",
    imagePreview: "",
    image: "",
    link: "",
    year: 2015,
    workTypes: ["design", "layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "TASS HRStat",
    type: "Website",
    description: "Information agency productivity statistics website",
    imagePreview: "",
    image: "",
    link: "",
    year: 2016,
    workTypes: ["layout", "coding"],
    status: ProjectStatus.Inactive,
  },
  {
    title: "Zip24 Service",
    type: "Website",
    description: "Brewery equipment",
    imagePreview: "",
    image: "",
    link: "https://zip24.ru",
    year: 2020,
    workTypes: ["coding"],
    status: ProjectStatus.Inactive,
  },
];
